@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package therealfarfetchd.qcommon.croco;

import javax.annotation.ParametersAreNonnullByDefault;

import therealfarfetchd.qcommon.MethodsReturnNonnullByDefault;